POSITION_MAPPING = {
    0: "QB",
    2: "RB",
    4: "WR",
    6: "TE",
    16: "D/ST",
    17: "K",
    23: "FLEX",
    20: "Bench",
    21: "IR",
    "": "NA",
}

POSITION_CODES = {1: "QB", 2: "RB", 3: "WR", 4: "TE", 16: "D/ST", 5: "K", "": "NA"}

STAT_MAPPING = {
    "0": "Pass Attempts",
    "1": "Completions",
    "3": "Pass Yards",
    "4": "Pass Touchdowns",
    "20": "Interceptions",
    "23": "Rushing Attempts",
    "24": "Rushing Yards",
    "25": "Rushing Touchdowns",
    "41": "Receptions",
    "42": "Receiving Yards",
    "43": "Receiving Touchdowns",
    "58": "Targets",
    "83": "Field Goals Made",
    "84": "Field Goals Attempted",
    "86": "Extra Points Made",
    "87": "Extra Points Attempted",
    "214": "Yards1",
    "216": "Yards2",
}

TEAM_ABBR_MAPPING = {
    "Commanders": "wsh",
    "49ers": "sf",
    "Cowboys": "dal",
    "Bills": "buf",
    "Dolphins": "mia",
    "Saints": "no",
    "Ravens": "bal",
    "Eagles": "phi",
    "Steelers": "pit",
    "Lions": "det",
    "Jets": "nyj",
    "Browns": "cle",
    "Patriots": "ne",
    "Chiefs": "kc",
    "Packers": "gb",
    "Texans": "hou",
    "Colts": "ind",
    "Bengals": "cin",
    "Buccaneers": "tb",
    "Seahawks": "sea",
    "Jaguars": "jax",
    "Panthers": "car",
    "Titans": "ten",
    "Broncos": "den",
    "Chargers": "lac",
    "Falcons": "atl",
    "Vikings": "min",
    "Giants": "nyg",
    "Bears": "chi",
    "Cardinals": "ari",
    "Raiders": "lv",
    "Rams": "lar",
}
